version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: qetta
      POSTGRES_PASSWORD: qetta
      POSTGRES_DB: qetta
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U qetta -d qetta"]
      interval: 3s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    volumes: [ "db_data:/var/lib/postgresql/data" ]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    command: ["redis-server","--appendonly","yes"]
    restart: unless-stopped
    volumes: [ "redis_data:/data" ]

  migrate:
    build:
      context: ../services/api
      dockerfile: Dockerfile
      target: deps
    env_file: ../.env
    depends_on:
      db:
        condition: service_healthy
    command: [ "sh", "-c", "npx prisma migrate deploy && node prisma/seed.js" ]

  api:
    build:
      context: ../services/api
      dockerfile: Dockerfile
      target: runtime
    env_file: ../.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    ports: ["8080:8080"]
    restart: unless-stopped

  web:
    build:
      context: ../services/web
      dockerfile: Dockerfile
    env_file: ../.env
    depends_on:
      api:
        condition: service_started
    ports: ["3000:3000"]
    restart: unless-stopped

volumes:
  db_data: {}
  redis_data: {}
