apiVersion: v1
kind: Service
metadata:
  name: qetta-api
  namespace: qetta-production
  labels:
    app: qetta
    component: api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3001
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app: qetta
    component: api
  sessionAffinity: None
