apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qetta-pdf-storage
  namespace: qetta-production
  labels:
    app: qetta
    component: storage
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: standard-rwx
  resources:
    requests:
      storage: 100Gi
